# Platform.py and Environ.py from http://www.iplt.org/
from Platform import *
from Environ import *
platform = GetPlatform()

env = Environment(LIBPATH  = "#lib", CPPPATH  = "#inc")
platform.SetCompilerFlags(env)
env.Append(CPPFLAGS = ['-g'])

Export('env')
Export('platform')

SConscript(dirs = ['estar', 'tools', 'pnf', 'gfx'])
