Import('env')
Import ('platform')

slist = ['Flow.cpp', 'PNFRiskMap.cpp', 'RobotShape.cpp', 'BufferZone.cpp',
         'pnf_cooc.c']
hlist = ['Flow.hpp', 'PNFRiskMap.hpp', 'RobotShape.hpp', 'BufferZone.hpp',
         'pnf_cooc.h']

env.StageLibrary(env.StaticLibrary('pnf', slist))
env.StageHeader('pnf', hlist)

e = env.Copy(LIBS = ['estar', 'pnf'])
e.StageBinary(e.Program(target = 'test_cooc', source = ['test_cooc.c']))
e.StageBinary(e.Program(target = 'test_riskmap', source=['test_riskmap.cpp']))

e = env.Copy(LIBS = ['estar', 'gfx', 'pnf'])
platform.SetGLStuff(e)
e.StageBinary(e.Program(target = 'test_flow', source = 'test_flow.cpp'))
