Import('env')
Import ('platform')

slist = ['Subwindow.cpp',
         'Viewport.cpp',
         'wrap_glu.cpp',
         'MetaMousehandler.cpp',
         'graphics.cpp']

hlist = ['Subwindow.hpp',
         'Viewport.hpp',
         'wrap_glu.hpp',
         'MetaMousehandler.hpp',
         'Mousehandler.hpp',
         'wrap_gl.hpp',
         'wrap_glut.hpp',
         'graphics.hpp']

env.StageLibrary(env.StaticLibrary('gfx', slist))
env.StageHeader('gfx', hlist)
